### PR TITLE
Add uzlopak to performance team

### PR DESCRIPTION
**Pull request by Uzlopak**
Well, why not :)

### CODE REVIEW

**Review by anonrig — APPROVED** [review]

**Review by H4ad — APPROVED** [review]
Great work on https://github.com/nodejs/node/pull/49654

**Comment by anonrig** [comment]
You are doing an awesome job. Welcome!

**Comment by anonrig** [comment]
cc @nodejs/performance

**Comment by Uzlopak** [comment]
thanks :)

**Pull request merged**
